name: hourly-fetch
on:
  workflow_dispatch:  
  schedule:
    - cron: '0 * * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run scraper
        run: |
          source .venv/bin/activate
          pip install requests python-dotenv
          python fetch_courses.py >> fetch.log
