name: hourly-fetch

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '18 * * * *'

jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create venv & install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Fetch courses JSON
        run: |
          source .venv/bin/activate
          python fetch_courses.py >> fetch.log

      - name: Rebuild FAISS index
        run: |
          source .venv/bin/activate
          python build_index.py >> fetch.log

      - name: Stash generated JSON
        run: |
          mv course_results.json /tmp/course_results.json

      - name: Switch to gh-pages
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          git clean -fd

      - name: Restore JSON
        run: |
          cp /tmp/course_results.json course_results.json

      - name: Commit & push to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add course_results.json
          git commit -m "chore: update course_results.json [skip ci]" || echo "No changes"
          git push origin gh-pages --force
